controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
search:
    path: /search
    methods: [POST]
    controller: App\Controller\AccueilController::search

filter_cars:
    path: /filter-cars
    controller: App\Controller\AccueilController::filterCars
    methods: [POST]

contact:
    path: /contact/{id}
    controller: App\Controller\ContactController::Contact
    methods: [GET, POST]
