controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
search:
    path: /search
    methods: [POST]
    controller: App\Controller\AccueilController::search

contact:
    path: /contact/{id}
    controller: App\Controller\ContactController::Contact
    methods: [GET, POST]

voiture_new:
    path: /voiture/new
    controller: App\Controller\VoitureController::new
    methods: [GET, POST]


